parameters:
    DEFAULT_DRIVER: pdo_pgsql
    DEFAULT_HOST: "127.0.0.1"
    DEFAULT_NAME: ldap
    DEFAULT_USER: ldap

doctrine:
    dbal:
        driver: '%env(string:default:DEFAULT_DRIVER:DATABASE_DRIVER)%'
        host: '%env(string:default:DEFAULT_HOST:DATABASE_HOST)%'
        dbname: '%env(string:default:DEFAULT_NAME:DATABASE_NAME)%'
        user: '%env(string:default:DEFAULT_USER:DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        server_version: '%env(DATABASE_SERVER_VERSION)%'
        charset: utf8

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        controller_resolver:
            auto_mapping: false
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
