doctrine:
    dbal:
        driver: '%env(default::APP_DATABASE_DRIVER)%'
        host: '%env(default::APP_DATABASE_HOST)%'
        dbname: '%env(default::APP_DATABASE_NAME)%'
        user: '%env(default::APP_DATABASE_USER)%'
        password: '%env(default::APP_DATABASE_PASSWORD)%'
        server_version: '%env(default::APP_DATABASE_SERVER_VERSION)%'
        url: '%env(default::APP_DATABASE_URL)%'
#        charset: utf8

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

        # lock_keys table is used by lock component, which is used by rate limiter
        # permissions_view:
        #   - needs to be listed below in schema_ignore_classes, otherwise doctrine will try to create it as a table
        #   - also needs to be here so that liip-test-fixtures-bundle's ORMPurger doesn't try to empty the view
        schema_filter: ~^(?!(lock_keys|permissions_view))~
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        controller_resolver:
            auto_mapping: false
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        schema_ignore_classes:
            - 'App\Entity\PermissionsView'
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
