framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: 'doctrine://default'
            async_ldap:
                dsn: 'doctrine://default?queue_name=ldap-queue'
                retry_strategy:
                    delay: 1800000     # 30 min delay first time
                    multiplier: 2      # double the delay for each retry
                    max_delay: 7200000 # max delay 2 hours
            async_notify:
                dsn: 'doctrine://default?queue_name=govuk-notify'
                retry_strategy:
                    delay: 1800000     # 30 min delay first time
                    multiplier: 2      # double the delay for each retry
                    max_delay: 7200000 # max delay 2 hours
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'App\Messenger\AlphagovNotify\AbstractMessage': async_ldap
            'App\Messenger\AlphagovNotify\AbstractHighPrioMessage': async_notify

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
