# .github/workflows/php-security-audit.yml
name: PHP security Audit

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'composer.lock'
      - '.github/workflows/php-security-audit.yml'
  push:
    branches: [ master ]
    paths:
      - 'composer.lock'
      - '.github/workflows/php-security-audit.yml'

jobs:
  php-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cache
        uses: actions/cache@v4
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db

      - name: Symfony security checker
        uses: symfonycorp/security-checker-action@v5
