name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP environment
        uses: ./.github/actions/setup-php-env
      - name: Run PHPUnit tests
        run: bin/phpunit --testdox

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP environment
        uses: ./.github/actions/setup-php-env
      - name: Install PHPUnit dependency
        run: bin/phpunit --help > /dev/null
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
